stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw/test.csv
    - data/raw/train.csv
    params:
    - data_ingestion.test_size
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/test.csv
    - data/raw/train.csv
    - src/data/data_preprocessing.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
  feature_engineering:
    cmd: python src/features/features.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - src/features/features.py
    outs:
    - data/interim/test_bow.csv
    - data/interim/train_bow.csv
    params:
    - feature_engg.max_features
  model_training:
    cmd: python src/modelling/modelling.py
    deps:
    - data/interim/train_bow.csv
    - src/modelling/modelling.py
    outs:
    - models/random_forest_model.pkl
    params:
    - model_training.n_estimators
    - model_training.max_depth
  model_evaluation:
    cmd: python src/modelling/model_evaluation.py
    deps:
    - data/interim/test_bow.csv
    - models/random_forest_model.pkl
    - src/modelling/model_evaluation.py
    outs:
    - reports/metrics.json
